tips/tip_how_to_ask_for_help
awesome-tips/Flutter-Tips pull request #10
Opened 2019-10-28 13:47 UTC by talisk

#7

2019-10-28 14:35 UTC, Vadaski requested changes
文章有一处需要处理的重复内容，麻烦删除它，thanks！

2019-10-28 14:35 UTC, Vadaski commented on tips/tip_how_to_ask_for_help.md
> +若无法找到适合的 issue，请新建一个 issue，并在正文中贴上你的 `$ flutter doctor` 输出信息，详细描述产生问题的步骤，最好配以可以复现问题的最简代码。
这里需要删除重复内容；）

2019-10-28 14:37 UTC, Vadaski commented on tips/tip_how_to_ask_for_help.md
> +若无法找到适合的 issue，请新建一个 issue，并在正文中贴上你的 `$ flutter doctor` 输出信息，详细描述产生问题的步骤，最好配以可以复现问题的最简代码。
这里应该是一个未完成的语句，之前的 review 有误，抱歉

2019-10-29 02:09 UTC, talisk commented on tips/tip_how_to_ask_for_help.md
> +若无法找到适合的 issue，请新建一个 issue，并在正文中贴上你的 `$ flutter doctor` 输出信息，详细描述产生问题的步骤，最好配以可以复现问题的最简代码。
done @Vadaski

2019-10-29 02:15 UTC, merged

2019-10-29 02:16 UTC, Vadaski commented
LGTM