Tip how to find flutter page
awesome-tips/Flutter-Tips pull request #11
Opened 2019-10-28 13:48 UTC by talisk

#3 如何判断一个界面是 Flutter 构建的

2019-10-28 15:11 UTC, Vadaski requested changes
图片链接需要修改，辛苦啦

2019-10-28 15:11 UTC, Vadaski commented on tips/tip_how_to_find_flutter_page.md
> +![](%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E4%B8%80%E4%B8%AA%E7%95%8C%E9%9D%A2%E6%98%AF%20Flutter%20%E6%9E%84%E5%BB%BA%E7%9A%8401.png)
图片链接有些问题，麻烦修复一下

2019-10-29 02:09 UTC, talisk commented on tips/tip_how_to_find_flutter_page.md
> +![](%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E4%B8%80%E4%B8%AA%E7%95%8C%E9%9D%A2%E6%98%AF%20Flutter%20%E6%9E%84%E5%BB%BA%E7%9A%8401.png)
@Vadaski done

2019-10-29 12:28 UTC, Vadaski commented
LGTM

2019-10-29 12:28 UTC, merged