[完成原创] Flutter | 性能优化——如何避免应用 jank
awesome-tips/Flutter-Tips pull request #19
Opened 2019-10-29 00:34 UTC by Vadaski

2019-10-29 00:36 UTC, Vadaski commented
ref: #12

2019-10-29 01:41 UTC, Realank reviewed
鑫磊给力！有一些建议供参考～

2019-10-29 01:41 UTC, Realank commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +![](https://user-gold-cdn.xitu.io/2019/10/20/16de9af67e0cc723?w=415&h=894&f=gif&s=99566)
图片来源我们可能得斟酌一下，用掘金的图片，可能会挂掉，商量一下看是不是直接放到md文件同级目录好一些

2019-10-29 01:41 UTC, Realank commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
“通过异步处理我们可以把一个方法在执行过程中暂停”
这句不太理解，我理解把耗时操作放到异步处理可以不阻塞主线程，但是这里的“暂停”不知指什么？

2019-10-29 01:41 UTC, Realank commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +在 Android 中我们是不能在 主线程（UI线程）中进行耗时操作的，如果做一些比较繁重的操作，比如网络请求、数据库操作等相关操作，就会导致 UI 线程卡住，触发 ANR。所以我们需要把这些操作放在子线程去做，通过 handler/looper/message queue 三板斧把结果传给主线程。而 dart 天生是单线程模式，为什么我们能够轻松的做这些任务，而不需要另开一个线程呢？
“而不需要另开一个线程呢？” 这里似乎和后面isolate开新的线程有所冲突

2019-10-29 01:41 UTC, Realank commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +Isolate 实际上是比较重的，每当我们创建出来一个新的 Isolate 至少需要 2mb 左右的空间甚至更多，取决于我们具体 isolate 的用途。
2mb最好是2MB，如果严格一些是2MiB

2019-10-29 01:46 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +![](https://user-gold-cdn.xitu.io/2019/10/20/16de9af67e0cc723?w=415&h=894&f=gif&s=99566)
哈哈 ok,我在一级目录下新建一个 pic 统一存放图片资源怎么样

2019-10-29 01:50 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +在 Android 中我们是不能在 主线程（UI线程）中进行耗时操作的，如果做一些比较繁重的操作，比如网络请求、数据库操作等相关操作，就会导致 UI 线程卡住，触发 ANR。所以我们需要把这些操作放在子线程去做，通过 handler/looper/message queue 三板斧把结果传给主线程。而 dart 天生是单线程模式，为什么我们能够轻松的做这些任务，而不需要另开一个线程呢？
嗯嗯，这里我在解释为什么 dart 处理**异步任务**不需要使用子线程（event loop），后面 isolate 是在处理繁重的 **同步任务**，彦博哥我这里是否需要再着重解释一下？

2019-10-29 01:50 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +Isolate 实际上是比较重的，每当我们创建出来一个新的 Isolate 至少需要 2mb 左右的空间甚至更多，取决于我们具体 isolate 的用途。
好的

2019-10-29 01:51 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
异步方法不会立即执行完毕，可以暂停，之后再来做（event loop），这里我的理解是否有问题？

2019-10-29 01:58 UTC, Realank commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
异步的方法除非代码主动暂停，否则不会“暂停”的，如果说暂停的话，也是CPU时间分片粒度的概念，我们线程是把时间分片抽象封装了，所以在线程粒度上来说，异步线程并不是通过暂停来让位更新UI的主线程的，主线程和其它线程同时运行，复杂操作在其它线程，不会干扰主线程更新UI。我的理解哈

2019-10-29 01:59 UTC, Realank commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +在 Android 中我们是不能在 主线程（UI线程）中进行耗时操作的，如果做一些比较繁重的操作，比如网络请求、数据库操作等相关操作，就会导致 UI 线程卡住，触发 ANR。所以我们需要把这些操作放在子线程去做，通过 handler/looper/message queue 三板斧把结果传给主线程。而 dart 天生是单线程模式，为什么我们能够轻松的做这些任务，而不需要另开一个线程呢？
这里话术可能对初学者而言有点混乱～最好优化一下～

2019-10-29 01:59 UTC, Realank commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +![](https://user-gold-cdn.xitu.io/2019/10/20/16de9af67e0cc723?w=415&h=894&f=gif&s=99566)
好主意～

2019-10-29 02:00 UTC, talisk requested changes

2019-10-29 02:00 UTC, talisk commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +这里假设先有一个需要在其他 isolate 中执行的方法，入参是一个 SendPort。需要注意的是,这里的方法**只能是顶层方法或静态方法**，所以我们这里使用了 static 修饰，并让其变成一个私有方法("_")。它的返回值也只能是 void，你可能会问，那我们如何获得结果呢？
这里的_需要转义，后文被渲染成斜体

2019-10-29 02:00 UTC, talisk commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +这里假设先有一个需要在其他 isolate 中执行的方法，入参是一个 SendPort。需要注意的是,这里的方法**只能是顶层方法或静态方法**，所以我们这里使用了 static 修饰，并让其变成一个私有方法("_")。它的返回值也只能是 void，你可能会问，那我们如何获得结果呢？
另外作为建议，可以使用``代码块包裹。即`_`

2019-10-29 02:30 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +![](https://user-gold-cdn.xitu.io/2019/10/20/16de9af67e0cc723?w=415&h=894&f=gif&s=99566)
done

2019-10-29 02:30 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +在 Android 中我们是不能在 主线程（UI线程）中进行耗时操作的，如果做一些比较繁重的操作，比如网络请求、数据库操作等相关操作，就会导致 UI 线程卡住，触发 ANR。所以我们需要把这些操作放在子线程去做，通过 handler/looper/message queue 三板斧把结果传给主线程。而 dart 天生是单线程模式，为什么我们能够轻松的做这些任务，而不需要另开一个线程呢？
好嘞

2019-10-29 02:31 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +这里假设先有一个需要在其他 isolate 中执行的方法，入参是一个 SendPort。需要注意的是,这里的方法**只能是顶层方法或静态方法**，所以我们这里使用了 static 修饰，并让其变成一个私有方法("_")。它的返回值也只能是 void，你可能会问，那我们如何获得结果呢？
ok，thanks！

2019-10-29 02:35 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +这里假设先有一个需要在其他 isolate 中执行的方法，入参是一个 SendPort。需要注意的是,这里的方法**只能是顶层方法或静态方法**，所以我们这里使用了 static 修饰，并让其变成一个私有方法("_")。它的返回值也只能是 void，你可能会问，那我们如何获得结果呢？
done

2019-10-29 06:59 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
我觉得这个问题咱们可以深入探讨一哈 🤣
先是异步，dart 单线程可以完成异步操作，我觉得原因在于 isolate 中有自己的 event loop，它把 异步方法切碎，变得非常细。一个异步方法中可能又涉及多个异步调用。然后 event loop 实际上是一个 优先级机制，决定了什么代码可以先运行，什么代码需要等待。也就是说，一个 异步方法会被切碎在多个时间点上执行，最后当所有执行完成了之后，Future complete。那么执行一个异步方法的时候，中途可以“暂停”，去执行同步方法，同步方法执行完毕后，再依次从 event loop 中取异步方法执行。这样异步方法就不会阻塞同步方法。我这里的暂停指的这个意思，

而 多线程，dart 中实际上 isolate 底层还是 OSThread 实现，现在可以确定的有，一个 OSThread 同一时间只能 enter 一个 Isolate，如果要访问另一个 Isolate 需要离开当前 Isolate，再 attach 另一个 Isolate。你这里说的子线程是否是 CPU 时间分片粒度，应该是其中的一种情况。具体我参考了这篇文章：https://mrale.ph/dartvm/

> The relationship between OS threads and isolates is a bit blurry and highly dependent on how VM is embedded into an application. Only the following is guaranteed:

> an OS thread can enter only one isolate at a time. It has to leave current isolate if it wants to enter another isolate;
there can only be a single mutator thread associated with an isolate at a time. Mutator thread is a thread that executes Dart code and uses VM's public C API.

我认为他的意思是，多线程是 CPU 时间分片实现还是真正多核并发，具体要看 DartVM 是如何嵌入应用的，也就是说，多核并行操作应该是可能的。Isolate 的 Port 机制中间 copy 经过 dart VM 的 heap 区域，只是copy值。

2019-10-29 07:14 UTC, Realank commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
是这样的哈哈，你讲解的很详细，从线程层到底层，包括是CPU时间分片还是多核。原理确实如此，任何线程在某一时刻都可能会被暂停，但是如果我们只谈线程这一层的话。时间粒度通常不会再去深入那么细，而是说子线程优先级低于主线程，或者说两个线程没有干扰，所以不影响UI更新。这是我的理解。另外，我没有看到过文章提到dart 单线程可以完成异步操作，不管dart的异步操作是通过C语言的线程实现的，还是event loop自己实现的，其实都是多线程的原理，我觉得都可以认为是多线程。不过这些都是观察角度的差别，没太大关系，我只是觉得“暂停”对子线程本身而言其实是不可见的。不过可能我的理解有偏差，你可能指的暂停是await语句等待后面的方法返回后，才继续往下走？

2019-10-29 07:16 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
@talisk 恺哥来帮忙看看呢

2019-10-29 07:30 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
是的，我就是说的 await 这种情况可能不会立即执行 🤣

2019-10-29 08:09 UTC, Realank commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
soga，那没问题了哈哈

2019-10-29 09:56 UTC, talisk commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
所以这里的措辞，还是用暂停吗？

> 通过异步处理我们可以把一个方法在执行过程中暂停

我按照原文语境进行理解，暂停更多的是针对抽象的任务，也就是说任务暂停了，但底层是如何实现的，到底有没有“停”，取决于 VM 的实现。

2019-10-29 12:16 UTC, Vadaski commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
> 通过异步处理我们可以把一个方法延迟执行
各位觉得这样如何？@talisk @Realank

2019-10-30 01:29 UTC, Realank commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
我看行～

2019-10-30 01:34 UTC, talisk commented on articles/Flutter  性能优化——如何避免应用 jank.md
> +熟悉 dart 的同学肯定了解 event loop 机制了，通过异步处理我们可以把一个方法在执行过程中暂停，首先保证我们的同步方法能够按时执行（这也是为什么 setState 中只能进行同步操作的缘故）。而整个 pipline 是一次同步的任务，所以异步任务就会暂停，等待 pipline 执行结束，这样就不会因为进行耗时操作卡住 UI。
可以

2019-10-30 11:24 UTC, talisk approved these changes

2019-10-30 11:24 UTC, talisk commented
LGTM

2019-10-30 14:24 UTC, merged