[完成原创] Flutter | 深入理解BuildContext.md
awesome-tips/Flutter-Tips pull request #27
Opened 2019-11-02 06:02 UTC by Vadaski

ref: #17

2019-11-04 01:41 UTC, Realank commented on articles/Flutter   深入理解BuildContext.md
> +在Flutter中，Everything is Widget，我们通过构造函数嵌套Widget来编写UI界面。实际上，Widget并不是真正要显示在屏幕上的东西,只是一个配置信息，它永远是immutable的，并且可以在多处重复使用。那真正显示在屏幕上的视图树是什么呢？Element Tree！
显示在屏幕上的是Render Object Tree吧？不过我理解你的意思，是想引出Element Tree~

2019-11-04 10:10 UTC, Vadaski commented on articles/Flutter   深入理解BuildContext.md
> +在Flutter中，Everything is Widget，我们通过构造函数嵌套Widget来编写UI界面。实际上，Widget并不是真正要显示在屏幕上的东西,只是一个配置信息，它永远是immutable的，并且可以在多处重复使用。那真正显示在屏幕上的视图树是什么呢？Element Tree！
哈哈，是的。我需要修改吗

2019-11-04 10:33 UTC, talisk requested changes

2019-11-04 10:33 UTC, talisk commented on articles/Flutter   深入理解BuildContext.md
> +压一个新的页面到屏幕上
这行中文在代码块中，是注释吗？

2019-11-04 10:33 UTC, talisk commented on articles/Flutter   深入理解BuildContext.md
> +把路由顶层的页面移除
这行中文在代码块中，是注释吗？

2019-11-04 10:33 UTC, talisk commented on articles/Flutter   深入理解BuildContext.md
> +一眼看上去好像没什么问题，解决方式也很简单，把home部分作为一个新的Widget拆出来就可以了。
建议全文中英文字符间加 ` ` 空格

2019-11-04 10:33 UTC, talisk commented on articles/Flutter   深入理解BuildContext.md
> +...
此行建议改为注释，不然可能在部分渲染器中导致代码块高亮渲染异常

2019-11-04 10:33 UTC, talisk commented on articles/Flutter   深入理解BuildContext.md
> +在Flutter中，Everything is Widget，我们通过构造函数嵌套Widget来编写UI界面。实际上，Widget并不是真正要显示在屏幕上的东西,只是一个配置信息，它永远是immutable的，并且可以在多处重复使用。那真正显示在屏幕上的视图树是什么呢？Element Tree！
> Widget并不是真正要显示在屏幕上的东西,

结尾处的 `,` 应为全角

2019-11-04 13:16 UTC, Vadaski commented on articles/Flutter   深入理解BuildContext.md
> +压一个新的页面到屏幕上
我之前写这里的代码块仅为使用高亮效果，所以这里的中文并没有添加注释。

2019-11-04 13:19 UTC, Vadaski commented on articles/Flutter   深入理解BuildContext.md
> +一眼看上去好像没什么问题，解决方式也很简单，把home部分作为一个新的Widget拆出来就可以了。
好提议～

2019-11-04 13:20 UTC, Vadaski commented on articles/Flutter   深入理解BuildContext.md
> +...
ok

2019-11-05 03:13 UTC, Realank commented on articles/Flutter   深入理解BuildContext.md
> +在Flutter中，Everything is Widget，我们通过构造函数嵌套Widget来编写UI界面。实际上，Widget并不是真正要显示在屏幕上的东西,只是一个配置信息，它永远是immutable的，并且可以在多处重复使用。那真正显示在屏幕上的视图树是什么呢？Element Tree！
最好能完善一下话术，比如真正持有“屏幕上的视图”/“UI控件”树是element tree等

2019-11-06 03:49 UTC, talisk approved these changes

2019-11-06 03:49 UTC, talisk commented
LGTM，@Realank 看下还有啥问题吗

2019-11-06 04:33 UTC, Vadaski commented on articles/Flutter   深入理解BuildContext.md
> +在Flutter中，Everything is Widget，我们通过构造函数嵌套Widget来编写UI界面。实际上，Widget并不是真正要显示在屏幕上的东西,只是一个配置信息，它永远是immutable的，并且可以在多处重复使用。那真正显示在屏幕上的视图树是什么呢？Element Tree！
ok

2019-11-06 06:36 UTC, Realank commented
鑫磊给力～

2019-11-06 06:36 UTC, merged