[任务完成] Flutter Widget - Container 布局详解
awesome-tips/Flutter-Tips pull request #34
Opened 2019-11-20 07:33 UTC by Realank

2019-11-25 07:23 UTC, Vadaski reviewed
一点小建议供彦博哥参考～

2019-11-25 07:23 UTC, Vadaski commented on articles/Flutter Widget - Container 布局详解
> +### 1. 参考文献
我的参考文献一般放在尾部，供参考哈哈

2019-11-25 07:23 UTC, Vadaski commented on articles/Flutter Widget - Container 布局详解
> +在Flutter中，所有的功能都被分散成单一功能的Widget，比如居中有Center，边框有Padding，文字是Text，手势是GestureDetector，他们各自维护一个功能，但是我们商业App的UI都很精美，如果要实现一个很好的布局，需要嵌套非常多的布局Widget，所以Container应运而生：
中英文之间增加空格会带来更好的阅读体验；）

2019-11-25 07:30 UTC, talisk requested changes

2019-11-25 07:30 UTC, talisk commented on articles/Flutter Widget - Container 布局详解
> +根据官网的介绍，Container会首先使用设置的padding来围绕子部件，然后对padding的大小添加额外的约束(如果非空)，然后Container被外部的空白区域（margin）包围。在绘制过程中，Container首先应用变换(transform)，然后绘制装饰(decoration)来填充区域，接着绘制子部件，最后绘制前景装饰(foregroundDecoration)，同时填充该区
注意中英文标点符号，

最后绘制前景装饰(foregroundDecoration) => 最后绘制前景装饰（foregroundDecoration）

2019-11-25 07:30 UTC, talisk commented on articles/Flutter Widget - Container 布局详解
> +- 在某些情况下，赋给widget的约束是无限制(unbounded)的，或者说是无限(infinite)的。也就是说，最大宽度和最大高度，都是double.INFINITY。
注意中英文标点符号
赋给widget的约束是无限制(unbounded)的，或者说是无限(infinite)的 => 赋给widget的约束是无限制（unbounded）的，或者说是无限（infinite）的

2019-11-25 07:30 UTC, talisk commented on articles/Flutter Widget - Container 布局详解
> +***A convenience widget that combines common painting, positioning, and sizing widgets.***
这里建议使用 Quote 语法，而不是加粗

2019-11-25 07:30 UTC, talisk commented on articles/Flutter Widget - Container 布局详解
> +
最后这里空行可能有点多

2019-11-25 08:55 UTC, Realank commented on articles/Flutter Widget - Container 布局详解
> +在Flutter中，所有的功能都被分散成单一功能的Widget，比如居中有Center，边框有Padding，文字是Text，手势是GestureDetector，他们各自维护一个功能，但是我们商业App的UI都很精美，如果要实现一个很好的布局，需要嵌套非常多的布局Widget，所以Container应运而生：
已改，超级累哈哈

2019-11-25 08:55 UTC, Realank commented on articles/Flutter Widget - Container 布局详解
> +根据官网的介绍，Container会首先使用设置的padding来围绕子部件，然后对padding的大小添加额外的约束(如果非空)，然后Container被外部的空白区域（margin）包围。在绘制过程中，Container首先应用变换(transform)，然后绘制装饰(decoration)来填充区域，接着绘制子部件，最后绘制前景装饰(foregroundDecoration)，同时填充该区
感谢细致观察

2019-11-25 08:56 UTC, Realank commented
感谢鑫磊和孙凯的纠错，观察太细致了，已经修改，请查阅哈哈

2019-11-26 12:39 UTC, Vadaski requested changes
还要再改改，哈哈

2019-11-26 12:39 UTC, Vadaski commented on articles/Flutter Widget - Container 布局详解
> +在 Flutter 中，所有的功能都被分散成单一功能的 Widget，比如居中有Center，边框有 Padding，文字是 Text，手势是 GestureDetector，他们各自维护一个功能，但是我们商业 App 的 UI 都很精美，如果要实现一个很好的布局，需要嵌套非常多的布局 Widget，所以 Container 应运而生：
center 前面需要一个空格

2019-11-26 12:39 UTC, Vadaski commented on articles/Flutter Widget - Container 布局详解
> +Flutter是树状渲染结构，首先从根结点开始渲染，从上到下传递约束，直到最终的叶子节点(没有子节点了)，然后叶子节点根据约束确定自身大小，然后将大小返回给上级结点，然后上一级根据叶子节点的尺寸，决定自己的大小，再返回上一级，最终根节点确定了大小。之后，根结点逐级往下摆放子节点的位置（根据子节点及子节点兄弟节点的大小和偏移量）。
Flutter 后需要空格

2019-11-26 12:39 UTC, Vadaski commented on articles/Flutter Widget - Container 布局详解
> +如果 Container 的约束是有限制的，那么没有子部件的 Container 会尝试尽可能大，如果Container的约束是没有限制的（unbounded），它就会尽可能小。
Container 前后需要空格

2019-11-27 00:56 UTC, Realank commented on articles/Flutter Widget - Container 布局详解
> +如果 Container 的约束是有限制的，那么没有子部件的 Container 会尝试尽可能大，如果Container的约束是没有限制的（unbounded），它就会尽可能小。
哈哈，已改，还发现另外两处

2019-11-27 00:58 UTC, Realank commented
已改英文周围空格～

2019-11-27 15:00 UTC, Vadaski commented
LGTM～

2019-11-27 15:00 UTC, merged